### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by tawsif93** [SkyTreasure/Airbnb-Map-View#4]
Your app showing error in the database link is provided. Cannot find the firebase app.

**Comment by SkyTreasure** [comment]
Hi Tawsif, you can create a sample firebase app in your firebase account with the same package name and add the google_services.json to the app folder. And also enable the required API's like places api, map api in the api console.

**Comment by tawsif93** [comment]
Thanks for your suggestions. It would be helpful if you can provide the address.json file format which i can use.

**Comment by SkyTreasure** [comment]
I don't think i have used address.json anywhere!

**Comment by tawsif93** [comment]
[Network call  addresses.json ](https://github.com/SkyTreasure/Airbnb-Android-Google-Map-View/blob/master/app/src/main/java/com/purvotara/airbnbmapexample/constants/NetworkConstants.java) in this file.

**Comment by SkyTreasure** [comment]
> {
  "address":[
    {
      "address_id":1,
      "mPincode":"560024",
      "city":"Bangalore",
      "line_1":"Vidhana Sowdha",
      "line_2":"Bangalore",
      "longitude":"77.593059",
      "latitude":"12.979803",
      "address_type":"",
      "default":true,
      "image":"http://kla.kar.nic.in/images/fullvs.jpg",
      "rating":"4.2",
      "distance":"5.0"
    },
    {
      "address_id":2,
      "mPincode":"560024",
      "city":"Bangalore",
      "line_1":"Lal Bagh Gardens",
      "line_2":"Bangalore",
      "longitude":"77.584788",
      "latitude":"12.950733",
      "address_type":"Garden",
      "default":true,
      "image":"http://journeymart.com/de/AttrationImages/lalbagh-botanical-garden.jpg",
      "rating":"4.2",
      "distance":"5.0"
    },
     
    {
      "address_id":4,
      "mPincode":"560024",
      "city":"Bangalore",
      "line_1":"Orion mall",
      "line_2":"Bangalore",
      "longitude":"77.554870",
      "latitude":"13.011060",
      "address_type":"",
      "default":true,
      "image":"http://media.gettyimages.com/videos/brigade-gateway-apartment-and-orion-mall-at-night-zoom-out-video-id503020939?s=640x640",
      "rating":"5.0",
      "distance":"6.0"
    },
    {
      "address_id":5,
      "mPincode":"560024",
      "city":"Bangalore",
      "line_1":"Iskon Temple",
      "line_2":"Bangalore",
      "longitude":"77.551039",
      "latitude":"13.009643",
      "address_type":"",
      "default":true,
      "image":"https://media-cdn.tripadvisor.com/media/photo-s/02/4c/72/9a/iskcon-bangalore-a-spiritual.jpg",
      "rating":"4.2",
      "distance":"7.0"
    },{
      "address_id":1,
      "mPincode":"560024",
      "city":"Bangalore",
      "line_1":"",
      "line_2":"",
      "longitude":"",
      "latitude":"",
      "address_type":"",
      "default":true,
      "image":"",
      "rating":"4.2",
      "distance":"5.0"
    },
    {
      "address_id":3,
      "mPincode":"560024",
      "city":"Bangalore",
      "line_1":"Cubbon Park",
      "line_2":"Bangalore",
      "longitude":"77.593132",
      "latitude":"12.976368",
      "address_type":"",
      "default":true,
      "image":"https://c1.staticflickr.com/1/211/518251727_1acf970ce7_z.jpg?zz=1",
      "rating":"4.3",
      "distance":"5.0"
    }
     
  ]
}

**Comment by tawsif93** [comment]
Thanks for your cooperation

**Comment by SkyTreasure** [comment]
Welcome :+1:
